# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2af9cc9a3d0e23bd53ae5f3a2b35e8b23e019831d3e4552ca93792287bad1c2c0bfee5b2c5179312cafc8a2ace6a299a16ae0a306cd30e10adbba10b8f6eaee3

test:
  secret_key_base: 20a24cba3578e76e9ba5ef65d4a1f42e8a3005d44fe9f6eb7f8ccdccd690693034c6681898c8c4e16e12876952b42baf0dfc281544a041a825cb33c6671ae45d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
